# Generated by Django 3.2.3 on 2021-06-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('Date', models.DateField()),
                ('complaint_type', models.CharField(max_length=50, null=True)),
                ('detail_complaint', models.CharField(max_length=300)),
            ],
        ),
    ]
